# Travis CI configuration
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/travis-lint

branches:
  only:
    - dev
    - gh-pages
language: node_js
node_js:
  - "4"
install:
  - "npm install"
script:
  - "npm test"
